---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: bosh-lite

inputs:
- name: capi-ci

run:
  path: capi-ci/ci/scripts/configure_route53_zone_delegation

params:
  AWS_DEFAULT_REGION: us-east-1
  DELEGATION_ACCESS_KEY_ID:
  DELEGATION_SECRET_ACCESS_KEY:
  DELEGATION_ZONE:
  ZONE_ACCESS_KEY_ID:
  ZONE_SECRET_ACCESS_KEY:
  ZONE:
