# from here: https://github.com/vito/oci-build-task
---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task
inputs:
- name: capi-kpack-watcher
outputs:
- name: image
run:
  path: build
