---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: pivotalcfreleng/tas-for-k8s-ci

inputs:
- name: image

outputs:
- name: labeled-image

run:
  path: bash
  args:
  - -euc
  - deplab --image-tar image/image.tar --output-tar "labeled-image/image.tar"
