releases:
- name: bosh-dns
  version: 0.0.7
  url: http://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=0.0.7
  sha1: 032fd263e940ec12589c920a348a004bd993b3c5

addons:
- name: bosh-dns
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      aliases:
        credhub.service.cf.internal: [ '*.credhub.default.cf.bosh' ]
