releases:
- name: bosh-dns
  sha1: 0d55ec52b3a5c54a8284388d2400bf4c0172d7af
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=0.0.8
  version: 0.0.8

addons:
- name: bosh-dns
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      aliases:
        credhub.service.cf.internal: [ '*.credhub.default.cf.bosh' ]
