releases:
- name: bosh-dns
  version: 0.0.8
  url: https://bosh.io/d/github.com/cloudfoundry/dns-release?v=0.0.8
  sha1: f43c79eea8115915f507ba3dd2936cb1ec33fdf4

addons:
- name: bosh-dns
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      aliases:
        credhub.service.cf.internal: [ '*.credhub.default.cf.bosh' ]
