---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/capi
    tag: cf-for-k8s

inputs:
- name: capi-ci
- name: capi-k8s-release
- name: capi-docker-image
- name: cf-api-watcher-docker-image
- name: nginx-docker-image
- name: cloud_controller_ng
- name: capi-nginx
- name: capi-kpack-watcher

outputs:
- name: updated-capi-k8s-release

params:
  GIT_COMMIT_EMAIL: capi-bot@pivotal.io
  GIT_COMMIT_USERNAME: "CAPI CI Bot"

run:
  path: capi-ci/ci/k8s/bump-capi-k8s-release-image-refs.sh
