platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi:bbl

inputs:
  - name: capi-ci
  - name: capi-ci-private

outputs:
  - name: kubeconfig

run:
  path: capi-ci/ci/k8s/extract-kubeconfig.sh

params:
  BBL_STATE_DIR:
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to root of the `bbl-state` input
  # - If unspecified, uses the root of the `bbl-state` input
