
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: go-units

inputs:
  - name: capi-kpack-watcher
  - name: capi-ci

params: {}

run:
  path: capi-ci/ci/k8s/run-capi-kpack-watcher-unit-tests.sh
