properties:
  template_only:
    aws:
      availability_zone: us-east-1a	 # e.g. us-east-1a
      availability_zone2: us-east-1c
      availability_zone3: us-east-1d
      subnet_ids:
        mysql1: subnet-3a40e861
        mysql2: subnet-0df14620
        mysql3: subnet-a5e285ec

iaas_settings:
  <<: (( merge || nil ))

  subnet_configs:
  - name: mysql1
    type: manual
    subnets:
    - range: 10.0.60.0/24
      reserved:
        - 10.0.60.2 - 10.0.60.9
        - 10.0.60.130 - 10.0.60.254
      static:
        - 10.0.60.10 - 10.0.60.14
      gateway: 10.0.60.1
      dns:
        - 10.0.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
      cloud_properties:
        subnet: (( properties.template_only.aws.subnet_ids.mysql1 ))
  - name: mysql2
    type: manual
    subnets:
    - range: 10.0.61.0/24
      reserved:
        - 10.0.61.2 - 10.0.61.9
        - 10.0.61.130 - 10.0.61.254
      static:
        - 10.0.61.10 - 10.0.61.14
      gateway: 10.0.61.1
      dns:
        - 10.0.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
      cloud_properties:
        subnet: (( properties.template_only.aws.subnet_ids.mysql2 ))
  - name: mysql3
    type: manual
    subnets:
    - range: 10.0.62.0/24
      reserved:
        - 10.0.62.2 - 10.0.62.9
        - 10.0.62.130 - 10.0.62.254
      static:
        - 10.0.62.10 - 10.0.62.14
      gateway: 10.0.62.1
      dns:
        - 10.0.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
      cloud_properties:
        subnet: (( properties.template_only.aws.subnet_ids.mysql3 ))

  stemcell: &stemcell
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
  compilation_workers: 4 # When setting this parameter, it overrides the default number of compilation workers (default=4)
  compilation_cloud_properties:
    instance_type: c4.large
    availability_zone: (( properties.template_only.aws.availability_zone ))
    ephemeral_disk:
      size: 30000 # in MB
      type: gp2
  resource_pool_cloud_properties:
  - name: mysql_z1
    cloud_properties:
      instance_type: m3.large
      availability_zone: (( properties.template_only.aws.availability_zone ))

  - name: mysql_z2
    cloud_properties:
      instance_type: m3.large
      availability_zone: (( properties.template_only.aws.availability_zone2 ))

  - name: mysql_z3
    cloud_properties:
      instance_type: m3.large
      availability_zone: (( properties.template_only.aws.availability_zone3 ))

  - name: arbitrator_z3
    cloud_properties:
      instance_type: t2.small
      availability_zone: (( properties.template_only.aws.availability_zone3 ))

  - name: proxy_z1
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( properties.template_only.aws.availability_zone ))

  - name: proxy_z2
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( properties.template_only.aws.availability_zone2 ))

  - name: cf-mysql-broker_z1
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( properties.template_only.aws.availability_zone ))

  - name: cf-mysql-broker_z2
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( properties.template_only.aws.availability_zone2 ))

  - name: errands_z1
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( properties.template_only.aws.availability_zone ))

  disk_pools:
  - name: mysql-persistent-disk
    disk_size: 100000
    cloud_properties:
      type: gp2
