platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v3.14.0

inputs:
  - name: capi-ci
  - name: capi-ci-private

outputs:
  - name: environment

run:
  path: capi-ci/ci/bbl-tasks/extract_bbl_environment.sh

params:
  ENV_NAME: ""
  DEPLOYMENT_NAME: cf
