---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
- name: capi-ci
- name: bbl-state

run:
  path: capi-ci/ci/bbl-tasks/update-runtime-config.sh

params:
  BBL_STATE_DIR:
  # - Optional
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to root of the `bbl-state` input
  # - If unspecified, uses the root of the `bbl-state` input
  RUNTIME_CONFIG_PATH:
  # - Required
  # - Path to the runtime config file
  # - relative to the BBL_STATE_DIR
  RUNTIME_CONFIG_NAME:
  # - Required
  # - Name for the runtime config
