groups:
- name: concourse
  jobs:
  - deploy-concourse

resources:
- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: capi-ci-private
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/capi-ci-private.git

- name: concourse
  type: github-release
  source:
    access_token: {{github_access_token}}
    repository: concourse
    user: concourse

- name: concourse-deployment
  type: bosh-deployment
  source:
    target: 34.192.151.213:25555
    username: {{ci_bosh_user}}
    password: {{ci_bosh_password}}
    deployment: concourse
    ignore_ssl: true

- name: concourse-config
  type: git
  source:
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/capi-ci-private.git

jobs:
- name: deploy-concourse
  serial: true
  interruptible: true
  plan:
  - aggregate:
    - get: concourse
      params:
        globs:
        - concourse-*.tgz
        - garden-runc-*.tgz
    - get: concourse-config
    - get: aws-stemcell
    - get: capi-ci-private
  - put: concourse-deployment
    params:
      manifest: concourse-config/ci/concourse.yml
      releases:
        - concourse/concourse-*.tgz
        - concourse/garden-runc-*.tgz
      stemcells:
        - aws-stemcell/*.tgz
