resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

resources:
  - name: terraform
    type: terraform
    source:
      storage:
        bucket: {{bosh_lite_storage_bucket}}
        bucket_path: bosh-lite/
        access_key_id: {{bosh_lite_storage_access_key}}
        secret_access_key: {{bosh_lite_storage_secret_key}}
        endpoint: storage.googleapis.com
  - name: capi-ci
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/capi-ci.git
  - name: bosh-deployment
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/bosh-deployment.git
  - name: pool
    type: pool
    source:
      branch: master
      uri: git@github.com:cloudfoundry/capi-ci-private.git
      pool: bosh-lites
      private_key: {{bosh_lite_pool_deploy_key}}

jobs:
  - name: create-bosh-lite
    plan:
      - aggregate:
        - get: capi-ci
        - get: bosh-deployment
      - put: terraform
        params:
          generate_random_name: true
          delete_on_failure: true
          terraform_source: capi-ci/ci/bosh-lite/terraform/
          vars:
            project_id: {{bosh_lite_project_id}}
            system_domain_suffix: {{bosh_lite_system_domain_suffix}}
            dns_zone_name: {{bosh_lite_dns_zone_name}}
            json_key: {{bosh_lite_gcp_json_key}}
      - task: create-bosh-lite
        file: capi-ci/ci/bosh-lite/scripts/create-bosh-lite.yml
        params:
          GCP_JSON_KEY: {{bosh_lite_gcp_json_key}}
      - task: upload-to-s3
        file: capi-ci/ci/bosh-lite/scripts/upload-to-s3.yml
        input_mapping:
          source-directory: director-state
        params:
          FILE_NAMES: "*-creds.yml *-state.json"
          AWS_ACCESS_KEY_ID: {{bosh_lite_storage_access_key}}
          AWS_SECRET_ACCESS_KEY: {{bosh_lite_storage_secret_key}}
          AWS_ENDPOINT: https://storage.googleapis.com
          S3_BUCKET: {{bosh_lite_storage_bucket}}
          S3_PATH: director-state
      - task: create-env-vars-file
        file: capi-ci/ci/bosh-lite/scripts/create-env-vars-file.yml
      - put: pool
        params:
          add: bosh-lite-env-info/
