groups:
- name: docker
  jobs:
  - rc-docs-docker
  - ruby-units-docker

resources:
- name: weekly
  type: time
  source:
    start: 23:00 -0700
    stop: 23:30 -0700
    days: [Sunday]

- name: capi-dockerfiles-rc-docs
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/capi-dockerfiles.git
    paths: [rc-docs/Dockerfile]
- name: docker-image-rc-docs
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: rc-docs
    username: {{dockerhub_user}}
    password: {{dockerhub_pass}}
    email: {{dockerhub_email}}

- name: capi-dockerfiles-ruby-units
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/capi-dockerfiles.git
    paths: [capi-ruby-units/Dockerfile]
- name: docker-image-ruby-units
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: ruby-units
    username: {{dockerhub_user}}
    password: {{dockerhub_pass}}
    email: {{dockerhub_email}}

jobs:
- name: rc-docs-docker
  serial: true
  plan:
  - aggregate:
    - get: weekly
      trigger: true
    - get: capi-dockerfiles-rc-docs
  - put: docker-image-rc-docs
    params:
      build: capi-dockerfiles-rc-docs/rc-docs
- name: ruby-units-docker
  serial: true
  plan:
  - aggregate:
    - get: weekly
      trigger: true
    - get: capi-dockerfiles-ruby-units
  - put: docker-image-ruby-units
    params:
      build: capi-dockerfiles-ruby-units/capi-ruby-units
