groups:
- name: concourse
  jobs:
  - update-bosh-concourse
  - deploy-concourse

resource_types:
- name: bosh2-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

- name: capi-ci-private
  type: git
  source:
    branch: master
    private_key: ((private_key))
    uri: git@github.com:cloudfoundry/capi-ci-private.git

- name: capi-ci
  type: git
  source:
    branch: master
    private_key: ((private_key))
    uri: git@github.com:cloudfoundry/capi-ci.git

- name: concourse
  type: github-release
  version: { tag: 'v3.6.0' }
  source:
    access_token: ((github_access_token))
    repository: concourse
    owner: concourse

- name: postgres
  type: bosh-io-release
  version: '21'
  source:
    access_token: ((github_access_token))
    repository: cloudfoundry/postgres-release

# Using Dave McClure's fork to get load-balancers for concourse from bbl
# We can switch back after this PR is merged: https://github.com/cloudfoundry/cf-deployment-concourse-tasks/pull/40/files
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: lb-type
    private_key: ((private_key))
    uri: git@github.com:mcwumbly/cf-deployment-concourse-tasks.git

- name: concourse-deployment
  type: bosh2-deployment
  source:
    deployment: concourse
    ignore_ssl: true

# Duplicates of capi-ci-private
- name: concourse-config
  type: git
  source:
    private_key: ((private_key))
    uri: git@github.com:cloudfoundry/capi-ci-private.git

- name: concourse-bbl-state
  type: git
  source:
    private_key: ((private_key))
    branch: master
    uri: git@github.com:cloudfoundry/capi-ci-private.git

# Scheduling
- name: weekly-sunday
  type: time
  source:
    location: America/Los_Angeles
    start: 23:00
    stop: 23:30
    days: [Sunday]

jobs:
- name: update-bosh-concourse
  serial: true
  plan:
    - aggregate:
      - get: cf-deployment-concourse-tasks
      - get: concourse-bbl-state
      - get: capi-ci
      - get: capi-ci-private
      - get: weekly-sunday
        trigger: true
    - task: update-bosh-concourse
      file: cf-deployment-concourse-tasks/bbl-up/task.yml
      input_mapping:
        bbl-state: concourse-bbl-state
        ops-files: capi-ci-private
        bbl-plan-patch: concourse-bbl-state
        # - Per the comment on bbl-up task.yml...If no patch is necessary, we suggest you use
        #   `input_mapping` to map your `bbl-state` resource
        #   to `bbl-plan-patch` in order to satisfy this
        #   required input.
      params:
        BBL_STATE_DIR: "ci"
        BBL_IAAS: "gcp"
        BBL_LB_CERT: "certs/ci.cf-app.com/certificate.crt"
        BBL_LB_KEY: "certs/ci.cf-app.com/certificate.key"
        BBL_LB_TYPE: "concourse"
        BBL_ENV_NAME: "concourse"
        BBL_GCP_SERVICE_ACCOUNT_KEY: ((ci_gcp_json_key))
        BBL_GCP_PROJECT_ID: ((ci_gcp_project_id))
        BBL_GCP_ZONE: ((ci_gcp_zone))
        BBL_GCP_REGION: ((ci_gcp_region))
      ensure:
        put: concourse-bbl-state
        params:
          repository: updated-bbl-state
          rebase: true
    - task: run-bosh-cleanup
      file: capi-ci/ci/bbl-tasks/run-bosh-cleanup.yml
      input_mapping:
        bbl-state: concourse-bbl-state
      params:
        BBL_STATE_DIR: "ci"

- name: deploy-concourse
  serial: true
  interruptible: true
  plan:
  - aggregate:
    - get: concourse
      params:
        globs:
        - concourse-*.tgz
        - garden-runc-*.tgz
    - get: postgres
    - get: concourse-config
    - get: gcp-stemcell
    - get: capi-ci-private
    - get: capi-ci
  - task: extract-bbl-environment
    file: capi-ci/ci/bbl-tasks/extract_bbl_environment.yml
    params:
      ENV_NAME: ci
      DEPLOYMENT_NAME: concourse
  - put: concourse-deployment
    params:
      source_file: environment/metadata
      manifest: concourse-config/ci/concourse.yml
      ops_files:
      - capi-ci/concourse-deployment-operations/gcp.yml
      releases:
        - concourse/concourse-*.tgz
        - concourse/garden-runc-*.tgz
        - postgres/*.tgz
      stemcells:
        - gcp-stemcell/*.tgz
      vars:
        ci_atc_certificate: ((ci_atc_certificate))
        ci_atc_private_key: ((ci_atc_private_key))
