groups:
- name: main
  jobs:
  - configure-buffy-networking
  - deploy-and-teardown-bosh-lite

resource_types:
- name: bosh-stemcell
  type: docker-image
  source:
    repository: cloudfoundry/bosh-stemcell-resource
- name: bosh-release
  type: docker-image
  source:
    repository: cloudfoundry/bosh-release-resource

resources:
- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: bosh-lite
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-lite.git

- name: bosh-lite-cf-deployment
  type: bosh-deployment
  source:
    username: admin
    password: admin
    deployment: cf-warden
    ignore_ssl: true

- name: bosh-lite-diego-deployment
  type: bosh-deployment
  source:
    username: admin
    password: admin
    deployment: cf-warden-diego
    ignore_ssl: true

- name: bosh-lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

- name: bosh-lite-stemcell-upload
  type: bosh-stemcell
  source:
    username: admin
    password: admin
    ignore_ssl: true

- name: bosh-lite-release-upload
  type: bosh-release
  source:
    username: admin
    password: admin
    ignore_ssl: true

- name: capi-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/capi-ci.git

- name: capi-ci-private
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/capi-ci-private.git

- name: capi-release
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/capi-release.git

- name: capi-release-tarball
  type: s3
  source:
    bucket: cf-capi-releases
    regexp: capi-(.*)-.{40}-.{40}.tgz
    access_key_id: {{wasabi_s3_access_key}}
    secret_access_key: {{wasabi_s3_secret_key}}

- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git

- name: cf-release-develop
  type: git
  source:
    branch: develop
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-release.git

- name: cf-release-tarball
  type: s3
  source:
    bucket: cf-runtime-releases
    regexp: cf-(\d+)-.*.tgz
    access_key_id: {{wasabi_s3_access_key}}
    secret_access_key: {{wasabi_s3_secret_key}}

- name: cflinuxfs2-rootfs-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry/cflinuxfs2-rootfs-release

- name: diego-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/diego-ci

- name: diego-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/diego-release.git

- name: diego-release-tarball
  type: s3
  source:
    bucket: diego-final-releases
    regexp: diego-(.*).tgz
    access_key_id: {{diego_s3_access_key}}
    secret_access_key: {{diego_s3_secret_key}}

- name: etcd-release-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/etcd-release

- name: garden-linux-release-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/garden-linux-release

jobs:
- name: deploy-and-teardown-bosh-lite
  plan:
  - aggregate:
    - get: bosh-lite
    - get: bosh-lite-stemcell
    - get: capi-ci
    - get: capi-ci-private
    - get: capi-release-tarball
    - get: cf-acceptance-tests
    - get: cf-release
      resource: cf-release-develop
      params:
        submodules: none
    - get: cf-release-tarball
    - get: cflinuxfs2-rootfs-tarball
    - get: cloud_controller_ng
      resource: cloud_controller_ng-migrate
      trigger: true
    - get: diego-release
      params:
        submodules: none
    - get: diego-release-tarball
    - get: etcd-release-tarball
    - get: garden-linux-release-tarball
  - task: ensure-bosh-lite-terminated
    file: capi-ci/ci/scripts/deprovision_bosh_lite.yml
    params:
      BOSH_LITE_NAME: buffy-bosh-lite
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
  - task: ensure-cloudformation-terminated
    file: capi-ci/ci/scripts/teardown_cloudformation_stack.yml
    params:
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      STACK_NAME: buffy-stack
  - task: create-cloudformation
    file: capi-ci/ci/scripts/create_cloudformation_stack.yml
    params:
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      STACK_NAME: buffy-stack
      CLOUDFORMATION_PATH: capi-ci/buffy/cloudformation.json
  - task: provision-bosh-lite
    file: capi-ci/ci/scripts/provision_bosh_lite.yml
    params:
      BOSH_LITE_INSTANCE_TYPE: c3.4xlarge
      BOSH_LITE_NAME: buffy-bosh-lite
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
      AWS_SECURITY_GROUP_TAG: {{buffy_security_group_tag}}
      AWS_SUBNET_NAME: {{buffy_subnet_name}}
      BOSH_LITE_KEYPAIR: {{buffy_keypair_name}}
      SSH_KEY: {{buffy_private_key}}
      APP_DOMAIN: buffy-apps.capi.cf-app.com
      SYSTEM_DOMAIN: buffy.capi.cf-app.com
  - task: generate-bosh-lite-cf-manifest
    file: capi-ci/ci/scripts/generate-bosh-lite-cf-manifest.yml
    params:
      ENVIRONMENT_STUB: capi-ci/buffy/stubs/cf/cf-stub.yml
      STUBS_PATH: deployments/stub.yml
  - aggregate:
    - put: bosh-lite-stemcell-upload
      params:
        target_file: deployments/target
        stemcells:
          - bosh-lite-stemcell/*.tgz
    - put: upload-cf-release-tarball
      resource: bosh-lite-release-upload
      params:
        target_file: deployments/target
        releases:
          - cf-release-tarball/*.tgz
    - put: upload-release-tarballs
      resource: bosh-lite-release-upload
      params:
        target_file: deployments/target
        releases:
          - capi-release-tarball/*.tgz
          - diego-release-tarball/*.tgz
          - garden-linux-release-tarball/*.tgz
          - etcd-release-tarball/*.tgz
          - cflinuxfs2-rootfs-tarball/*.tgz
  - put: bosh-lite-cf-deployment
    params:
      target_file: deployments/target
      manifest: generated-manifests/cf-deployment.yml
      stemcells:
        - bosh-lite-stemcell/*.tgz
      releases:
        - cf-release-tarball/*.tgz
        - capi-release-tarball/*.tgz
  - put: bosh-lite-diego-deployment
    params:
      target_file: deployments/target
      manifest: generated-manifests/diego-deployment.yml
      stemcells:
        - bosh-lite-stemcell/*.tgz
      releases:
        - capi-release-tarball/*.tgz
        - diego-release-tarball/*.tgz
        - garden-linux-release-tarball/*.tgz
        - etcd-release-tarball/*.tgz
        - cflinuxfs2-rootfs-tarball/*.tgz
  - task: terminate-cloudformation
    file: capi-ci/ci/scripts/teardown_cloudformation_stack.yml
    params:
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      STACK_NAME: buffy-stack

- name: configure-buffy-networking
  plan:
  - aggregate:
    - get: capi-ci
  - task: delete-cloudformation
    file: capi-ci/ci/scripts/teardown_cloudformation_stack.yml
    params:
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      STACK_NAME: buffy-hosted-zones
  - task: create-cloudformation
    file: capi-ci/ci/scripts/create_cloudformation_stack.yml
    params:
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      STACK_NAME: buffy-hosted-zones
      CLOUDFORMATION_PATH: capi-ci/buffy/cloudformation-hosted-zones.json
  - task: delegate-buffy-dns
    file: capi-ci/ci/scripts/configure_route53_zone_delegation.yml
    params:
      DELEGATION_ZONE: capi.cf-app.com.
      DELEGATION_ACCESS_KEY_ID: {{wasabi_route53_access_key}}
      DELEGATION_SECRET_ACCESS_KEY: {{wasabi_route53_secret_key}}
      ZONE_ACCESS_KEY_ID: {{buffy_access_key}}
      ZONE_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      ZONE: "buffy.capi.cf-app.com"
  - task: delegate-buffy-apps-dns
    file: capi-ci/ci/scripts/configure_route53_zone_delegation.yml
    params:
      DELEGATION_ZONE: capi.cf-app.com.
      DELEGATION_ACCESS_KEY_ID: {{wasabi_route53_access_key}}
      DELEGATION_SECRET_ACCESS_KEY: {{wasabi_route53_secret_key}}
      ZONE_ACCESS_KEY_ID: {{buffy_access_key}}
      ZONE_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      ZONE: "buffy-apps.capi.cf-app.com"
