groups:
- name: docker
  jobs:
  - rc-docs-docker
  - ruby-units-docker
  - go-units-docker
  - bbl-docker
  - bosh-lite-docker
  - spiff-docker
  - runtime-ci
  - sits-docker

resources:
- name: weekly
  type: time
  source:
    start: 23:00 -0700
    stop: 23:30 -0700
    days: [Sunday]

- name: capi-dockerfiles-rc-docs
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/capi-dockerfiles.git
    paths: [rc-docs/Dockerfile]

- name: docker-image-rc-docs
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: rc-docs
    username: ((dockerhub_user))
    password: ((dockerhub_pass))
    email: ((dockerhub_email))

- name: capi-dockerfiles-runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/capi-dockerfiles.git
    paths: [capi-runtime-ci/Dockerfile]

- name: capi-dockerfiles-sits
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/sync-integration-tests.git
    paths: [concourse/Dockerfile]

- name: docker-image-sits
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: sits
    username: ((dockerhub_user))
    password: ((dockerhub_pass))
    email: ((dockerhub_email))

- name: docker-image-runtime-ci
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: runtime-ci
    username: ((dockerhub_user))
    password: ((dockerhub_pass))
    email: ((dockerhub_email))

- name: capi-dockerfiles-ruby-units
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/capi-dockerfiles.git
    paths: [capi-ruby-units/Dockerfile]

- name: docker-image-ruby-units
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: ruby-units
    username: ((dockerhub_user))
    password: ((dockerhub_pass))
    email: ((dockerhub_email))

- name: capi-dockerfiles-go-units
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/capi-dockerfiles.git
    paths: [capi-go-units/Dockerfile]

- name: docker-image-go-units
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: go-units
    username: ((dockerhub_user))
    password: ((dockerhub_pass))
    email: ((dockerhub_email))

- name: capi-dockerfiles-bbl
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/capi-dockerfiles.git
    paths: [bbl/Dockerfile]

- name: docker-image-bbl
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: bbl
    username: ((dockerhub_user))
    password: ((dockerhub_pass))
    email: ((dockerhub_email))

- name: capi-dockerfiles-bosh-lite
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/capi-dockerfiles.git
    paths: [bosh-lite/Dockerfile]

- name: docker-image-bosh-lite
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: bosh-lite
    username: ((dockerhub_user))
    password: ((dockerhub_pass))
    email: ((dockerhub_email))

- name: capi-dockerfiles-spiff
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/capi-dockerfiles.git
    paths: [spiff/Dockerfile]

- name: docker-image-spiff
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: spiff
    username: ((dockerhub_user))
    password: ((dockerhub_pass))
    email: ((dockerhub_email))

jobs:
- name: rc-docs-docker
  serial: true
  plan:
  - aggregate:
    - get: weekly
      trigger: true
    - get: capi-dockerfiles-rc-docs
  - put: docker-image-rc-docs
    params:
      build: capi-dockerfiles-rc-docs/rc-docs
- name: ruby-units-docker
  serial: true
  plan:
  - aggregate:
    - get: weekly
      trigger: true
    - get: capi-dockerfiles-ruby-units
  - put: docker-image-ruby-units
    params:
      build: capi-dockerfiles-ruby-units/capi-ruby-units
- name: go-units-docker
  serial: true
  plan:
  - aggregate:
    - get: weekly
      trigger: true
    - get: capi-dockerfiles-go-units
  - put: docker-image-go-units
    params:
      build: capi-dockerfiles-go-units/capi-go-units
- name: bbl-docker
  serial: true
  plan:
  - aggregate:
    - get: weekly
      trigger: true
    - get: capi-dockerfiles-bbl
  - put: docker-image-bbl
    params:
      build: capi-dockerfiles-bbl/bbl
- name: runtime-ci
  serial: true
  plan:
  - aggregate:
    - get: weekly
      trigger: true
    - get: capi-dockerfiles-runtime-ci
  - put: docker-image-runtime-ci
    params:
      build: capi-dockerfiles-runtime-ci/capi-runtime-ci
- name: bosh-lite-docker
  serial: true
  plan:
  - aggregate:
    - get: weekly
      trigger: true
    - get: capi-dockerfiles-bosh-lite
  - put: docker-image-bosh-lite
    params:
      build: capi-dockerfiles-bosh-lite/bosh-lite
- name: spiff-docker
  serial: true
  plan:
  - aggregate:
    - get: weekly
      trigger: true
    - get: capi-dockerfiles-spiff
  - put: docker-image-spiff
    params:
      build: capi-dockerfiles-spiff/spiff
- name: sits-docker
  serial: true
  plan:
  - aggregate:
    - get: weekly
      trigger: true
    - get: capi-dockerfiles-sits
  - put: docker-image-sits
    params:
      build: capi-dockerfiles-sits/concourse
