groups:
- name: great-migration
  jobs:
  - cc-unit-tests-with-migrations
  - app-availability-during-migration
  - deploy-and-test-arya
- name: environment-setup
  jobs:
  - configure-buffy-networking

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
- name: bosh-stemcell
  type: docker-image
  source:
    repository: cloudfoundry/bosh-stemcell-resource
- name: bosh-release
  type: docker-image
  source:
    repository: cloudfoundry/bosh-release-resource

resources:

- name: version
  type: semver
  source:
    access_key_id: {{wasabi_semver_access_key}}
    secret_access_key: {{wasabi_semver_secret_key}}
    initial_version: 0.0.1
    bucket: capi-release-versions
    key: migrate-capi-release-version
    region_name: us-east-1

- name: arya-acceptance-tests-with-diego-logs
  type: s3
  source:
    private: true
    bucket: arya-acceptance-tests-with-diego-logs
    regexp: acceptance_tests.(0)..*.tgz
    access_key_id: {{arya_aws_access_key}}
    secret_access_key: {{arya_aws_secret_key}}

- name: arya-acceptance-tests-with-dea-logs
  type: s3
  source:
    private: true
    bucket: arya-acceptance-tests-with-dea-logs
    regexp: acceptance_tests.(0)..*.tgz
    access_key_id: {{arya_aws_access_key}}
    secret_access_key: {{arya_aws_secret_key}}

- name: arya-deployment
  type: bosh-deployment
  source:
    target: https://bosh.arya.cf-app.com:25555
    username: {{arya_bosh_user}}
    password: {{arya_bosh_password}}
    deployment: cf-arya
    ignore_ssl: true

- name: arya-diego-deployment
  type: bosh-deployment
  source:
    target: https://bosh.arya.cf-app.com:25555
    username: {{arya_bosh_user}}
    password: {{arya_bosh_password}}
    deployment: cf-arya-diego
    ignore_ssl: true

- name: arya-release-upload
  type: bosh-release
  source:
    target: https://bosh.arya.cf-app.com:25555
    username: {{arya_bosh_user}}
    password: {{arya_bosh_password}}
    ignore_ssl: true

- name: arya-stemcell-upload
  type: bosh-stemcell
  source:
    target: https://bosh.arya.cf-app.com:25555
    username: {{arya_bosh_user}}
    password: {{arya_bosh_password}}
    ignore_ssl: true

- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- name: bosh-lite
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-lite.git

- name: cf-mysql-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-mysql-release.git

- name: bosh-lite-mysql-deployment
  type: bosh-deployment
  source:
    username: admin
    password: admin
    deployment: cf-warden-mysql
    ignore_ssl: true

- name: bosh-lite-cf-deployment
  type: bosh-deployment
  source:
    username: admin
    password: admin
    deployment: cf-warden
    ignore_ssl: true

- name: bosh-lite-diego-deployment
  type: bosh-deployment
  source:
    username: admin
    password: admin
    deployment: cf-warden-diego
    ignore_ssl: true

- name: bosh-lite-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent

- name: bosh-lite-stemcell-upload
  type: bosh-stemcell
  source:
    username: admin
    password: admin
    ignore_ssl: true

- name: bosh-lite-release-upload
  type: bosh-release
  source:
    username: admin
    password: admin
    ignore_ssl: true

- name: capi-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/capi-ci.git

- name: capi-ci-private
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/capi-ci-private.git

- name: capi-release
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/capi-release.git

- name: capi-release-tarball
  type: s3
  source:
    bucket: cf-capi-releases
    regexp: capi-(.*)-.{40}-.{40}.tgz
    access_key_id: {{wasabi_s3_access_key}}
    secret_access_key: {{wasabi_s3_secret_key}}

- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git

- name: cf-release-develop
  type: git
  source:
    branch: develop
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cf-release.git

- name: cf-release-tarball
  type: s3
  source:
    bucket: cf-runtime-releases
    regexp: cf-(\d+)-.*.tgz
    access_key_id: {{wasabi_s3_access_key}}
    secret_access_key: {{wasabi_s3_secret_key}}

- name: cflinuxfs2-rootfs-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry/cflinuxfs2-rootfs-release

- name: cf-mysql-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-mysql-release

- name: cloud_controller_ng-migrate
  type: git
  source:
    branch: migrate
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/cloud_controller_ng.git

- name: cloud_controller_ng-migrate-migrations
  type: git
  source:
    branch: migrate
    uri: https://github.com/cloudfoundry/cloud_controller_ng.git
    paths: ['db']

- name: diego-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/diego-ci

- name: diego-release
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/diego-release.git

- name: diego-release-tarball
  type: s3
  source:
    bucket: diego-final-releases
    regexp: diego-(.*).tgz
    access_key_id: {{diego_s3_access_key}}
    secret_access_key: {{diego_s3_secret_key}}

- name: etcd-release-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/etcd-release

- name: garden-linux-release-tarball
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/garden-linux-release

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack_failure_hook_url}}

- name: slack-notice
  type: slack-notification
  source:
    url: {{slack_capi_hook_url}}

jobs:
- name: cc-unit-tests-with-migrations
  plan:
  - aggregate:
    - get: cloud_controller_ng
      resource: cloud_controller_ng-migrate
      trigger: true
    - get: capi-ci
  - aggregate:
    - task: run-cc-unit-tests-mysql
      file: capi-ci/ci/scripts/run_cc_unit_tests.yml
      params:
        DB: mysql
      on_failure:
        put: slack-alert
        params:
          text: '[cc-unit-tests-with-migrations] OH NO! Failed when running with mysql'
          icon_emoji: {{slack_failure_emoji}}
    - task: run-cc-unit-tests-postgres
      file: capi-ci/ci/scripts/run_cc_unit_tests.yml
      params:
        DB: postgres
      on_failure:
        put: slack-alert
        params:
          text: '[cc-unit-tests-with-migrations] OH NO! Failed when running with postgres'
          icon_emoji: {{slack_failure_emoji}}

- name: app-availability-during-migration
  plan:
  - aggregate:
    - get: bosh-lite
    - get: bosh-lite-stemcell
    - get: capi-ci
    - get: capi-ci-private
    - get: capi-release-tarball
    - get: cf-acceptance-tests
    - get: cf-mysql-release
    - get: cf-release
      resource: cf-release-develop
      params:
        submodules: none
    - get: cf-release-tarball
    - get: cflinuxfs2-rootfs-tarball
    - get: cf-mysql-tarball
    - get: cloud_controller_ng
      resource: cloud_controller_ng-migrate
      trigger: true
    - get: diego-release
      params:
        submodules: none
    - get: diego-release-tarball
    - get: etcd-release-tarball
    - get: garden-linux-release-tarball
  - task: ensure-bosh-lite-terminated
    file: capi-ci/ci/scripts/deprovision_bosh_lite.yml
    params:
      BOSH_LITE_NAME: buffy-bosh-lite
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
  - task: ensure-cloudformation-terminated
    file: capi-ci/ci/scripts/teardown_cloudformation_stack.yml
    params:
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      STACK_NAME: buffy-stack
  - task: create-cloudformation
    file: capi-ci/ci/scripts/create_cloudformation_stack.yml
    params:
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      STACK_NAME: buffy-stack
      CLOUDFORMATION_PATH: capi-ci/buffy/cloudformation.json
  - task: provision-bosh-lite
    file: capi-ci/ci/scripts/provision_bosh_lite.yml
    params:
      BOSH_LITE_INSTANCE_TYPE: c3.4xlarge
      BOSH_LITE_NAME: buffy-bosh-lite
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
      AWS_SECURITY_GROUP_TAG: {{buffy_security_group_tag}}
      AWS_SUBNET_NAME: {{buffy_subnet_name}}
      BOSH_LITE_KEYPAIR: {{buffy_keypair_name}}
      SSH_KEY: {{buffy_private_key}}
      APP_DOMAIN: buffy-apps.capi.cf-app.com
      SYSTEM_DOMAIN: buffy.capi.cf-app.com
  - task: generate-bosh-lite-cf-manifest
    file: capi-ci/ci/scripts/generate-bosh-lite-cf-manifest.yml
    params:
      ENVIRONMENT_STUB: capi-ci/buffy/stubs/cf/cf-stub.yml
      STUBS_PATH: deployments/stub.yml
      MYSQL_PROPERTY_OVERRIDES_PATH: capi-ci-private/buffy/stubs/mysql/property-overrides.yml
      MYSQL_INSTANCE_COUNT_OVERRIDES_PATH: instance-count-overrides.yml
  - aggregate:
    - put: bosh-lite-stemcell-upload
      params:
        target_file: deployments/target
        stemcells:
          - bosh-lite-stemcell/*.tgz
    - put: upload-cf-release-tarball
      resource: bosh-lite-release-upload
      params:
        target_file: deployments/target
        releases:
          - cf-release-tarball/*.tgz
    - put: upload-release-tarballs
      resource: bosh-lite-release-upload
      params:
        target_file: deployments/target
        releases:
          - capi-release-tarball/*.tgz
          - diego-release-tarball/*.tgz
          - garden-linux-release-tarball/*.tgz
          - etcd-release-tarball/*.tgz
          - cflinuxfs2-rootfs-tarball/*.tgz
          - cf-mysql-tarball/*.tgz
  - put: bosh-lite-mysql-deployment
    params:
      target_file: deployments/target
      manifest: generated-manifests/mysql-deployment.yml
      releases:
        - cf-mysql-tarball/*.tgz
  - put: bosh-lite-cf-deployment
    params:
      target_file: deployments/target
      manifest: generated-manifests/cf-deployment.yml
      stemcells:
        - bosh-lite-stemcell/*.tgz
      releases:
        - cf-release-tarball/*.tgz
        - capi-release-tarball/*.tgz
  - put: bosh-lite-diego-deployment
    params:
      target_file: deployments/target
      manifest: generated-manifests/diego-deployment.yml
      stemcells:
        - bosh-lite-stemcell/*.tgz
      releases:
        - capi-release-tarball/*.tgz
        - diego-release-tarball/*.tgz
        - garden-linux-release-tarball/*.tgz
        - etcd-release-tarball/*.tgz
        - cflinuxfs2-rootfs-tarball/*.tgz
  - task: app-availability-test
    file: capi-ci/ci/scripts/app_availability_test.yml
    params:
      API_DOMAIN: api.buffy.capi.cf-app.com
      APP_DOMAIN: buffy-apps.capi.cf-app.com
      CLOUD_CONTROLLER_BRANCH: migrate
      DB_NAME: {{buffy_cc_db_database}}
      DB: postgres
      DB_HOST: 10.244.0.30
      DB_USERNAME: {{buffy_cc_db_username}}
      DB_PASSWORD: {{buffy_cc_db_password}}
      ENVIRONMENT: buffy
      TUNNEL_HOST: bosh.buffy.capi.cf-app.com
    ensure:
      task: deprovision-bosh-lite
      file: capi-ci/ci/scripts/deprovision_bosh_lite.yml
      params:
        BOSH_LITE_NAME: buffy-bosh-lite
        AWS_ACCESS_KEY_ID: {{buffy_access_key}}
        AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
        AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
  - task: terminate-cloudformation
    file: capi-ci/ci/scripts/teardown_cloudformation_stack.yml
    params:
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      STACK_NAME: buffy-stack

- name: configure-buffy-networking
  plan:
  - aggregate:
    - get: capi-ci
  - task: delete-cloudformation
    file: capi-ci/ci/scripts/teardown_cloudformation_stack.yml
    params:
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      STACK_NAME: buffy-hosted-zones
  - task: create-cloudformation
    file: capi-ci/ci/scripts/create_cloudformation_stack.yml
    params:
      AWS_DEFAULT_REGION: {{buffy_aws_default_region}}
      AWS_ACCESS_KEY_ID: {{buffy_access_key}}
      AWS_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      STACK_NAME: buffy-hosted-zones
      CLOUDFORMATION_PATH: capi-ci/buffy/cloudformation-hosted-zones.json
  - task: delegate-buffy-dns
    file: capi-ci/ci/scripts/configure_route53_zone_delegation.yml
    params:
      DELEGATION_ZONE: capi.cf-app.com.
      DELEGATION_ACCESS_KEY_ID: {{wasabi_route53_access_key}}
      DELEGATION_SECRET_ACCESS_KEY: {{wasabi_route53_secret_key}}
      ZONE_ACCESS_KEY_ID: {{buffy_access_key}}
      ZONE_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      ZONE: "buffy.capi.cf-app.com"
  - task: delegate-buffy-apps-dns
    file: capi-ci/ci/scripts/configure_route53_zone_delegation.yml
    params:
      DELEGATION_ZONE: capi.cf-app.com.
      DELEGATION_ACCESS_KEY_ID: {{wasabi_route53_access_key}}
      DELEGATION_SECRET_ACCESS_KEY: {{wasabi_route53_secret_key}}
      ZONE_ACCESS_KEY_ID: {{buffy_access_key}}
      ZONE_SECRET_ACCESS_KEY: {{buffy_secret_key}}
      ZONE: "buffy-apps.capi.cf-app.com"

- name: deploy-and-test-arya
  serial: true
  plan:
  - aggregate:
    - get: cf-release-tarball
    - get: capi-release
    - get: cloud_controller_ng
      resource: cloud_controller_ng-migrate
    - get: version
      params:
        pre: migrate
    - get: capi-ci
    - get: capi-ci-private
    - get: aws-stemcell
    - get: cf-release
      resource: cf-release-develop
    - get: diego-ci
    - get: diego-release
      params:
        submodules: none
    - get: garden-linux-release-tarball
    - get: etcd-release-tarball
    - get: diego-release-tarball
    - get: cflinuxfs2-rootfs-tarball
  - put: version
    params:
      file: version/version
  - task: cf-manifest-with-dea
    privileged: true
    file: capi-ci/ci/scripts/create_cf_deployment_migration_manifest_with_dea.yml
    params:
      INFRASTRUCTURE: aws
      ENVIRONMENT: arya
  - task: cf-manifest-with-diego
    privileged: true
    file: capi-ci/ci/scripts/create_cf_deployment_migration_manifest_with_diego.yml
    params:
      INFRASTRUCTURE: aws
      ENVIRONMENT: arya
  - task: manifest-with-0-postgres
    privileged: true
    file: capi-ci/ci/scripts/create_cf_deployment_migration_manifest_with_0_postgres.yml
    params:
      INFRASTRUCTURE: aws
      ENVIRONMENT: arya
  - task: generate-diego-deployment-manifests
    file: capi-ci/ci/scripts/create_diego_release_for_migration_manifest.yml
    params:
      BOSH_TARGET: bosh.arya.cf-app.com
      BOSH_USER: {{arya_bosh_user}}
      BOSH_PASSWORD: {{arya_bosh_password}}
      DEPLOYMENTS_DIR: capi-ci-private
      ENVIRONMENT_NAME: arya
  - task: create-release-tarball
    file: capi-ci/ci/scripts/create_capi_release.yml
    params:
      CC_BRANCH: migrate
  - aggregate:
    - put: arya-stemcell-upload
      params:
        stemcells:
          - aws-stemcell/*.tgz
    - put: upload-cf-release-tarball
      resource: arya-release-upload
      params:
        releases:
          - cf-release-tarball/*.tgz
    - put: upload-release-tarballs
      resource: arya-release-upload
      params:
        releases:
          - created-capi-release/capi-*.tgz
          - diego-release-tarball/*.tgz
          - garden-linux-release-tarball/*.tgz
          - etcd-release-tarball/*.tgz
          - cflinuxfs2-rootfs-tarball/*.tgz
  - put: arya-deployment
    params:
      manifest: generated-manifest-with-0-postgres/deployment_with_0_postgres.yml
      stemcells: [aws-stemcell/*.tgz]
      releases:
        - cf-release-tarball/*.tgz
        - created-capi-release/capi-*.tgz
  - put: arya-deployment
    params:
      manifest: generated-manifest-with-dea/cf-deployment-with-dea.yml
      stemcells: [aws-stemcell/*.tgz]
      releases:
        - cf-release-tarball/*.tgz
        - created-capi-release/capi-*.tgz
  - put: arya-diego-deployment
    params:
      manifest: generated-diego-manifest/diego-deployment.yml
      releases:
        - diego-release-tarball/*.tgz
        - garden-linux-release-tarball/*.tgz
        - etcd-release-tarball/*.tgz
        - cflinuxfs2-rootfs-tarball/*.tgz
      stemcells: [aws-stemcell/*.tgz]
  - task: enable-feature-flags
    file: capi-ci/ci/scripts/enable_feature_flags.yml
    params:
      CF_ADMIN_PASSWORD: {{arya_cf_admin_password}}
  - task: dea-acceptance-tests
    privileged: true
    file: capi-ci/ci/scripts/run_bosh_command.yml
    input_mapping: {manifest: generated-manifest-with-dea}
    params:
      BOSH_DIRECTOR: bosh.arya.cf-app.com
      BOSH_USER: {{arya_bosh_user}}
      BOSH_PASSWORD: {{arya_bosh_password}}
      DEPLOYMENT_YML: manifest/cf-deployment-with-dea.yml
      COMMAND: 'run errand acceptance_tests --keep-alive --download-logs --logs-dir bosh-logs'
    ensure:
      put: arya-acceptance-tests-with-dea-logs
      params:
        file: bosh-logs/acceptance_tests*.tgz
  - put: arya-deployment
    params:
      manifest: generated-manifest-with-diego/cf-deployment-with-diego.yml
      stemcells: [aws-stemcell/*.tgz]
      releases:
        - cf-release-tarball/*.tgz
        - created-capi-release/capi-*.tgz
  - task: diego-acceptance-tests
    privileged: true
    file: capi-ci/ci/scripts/run_bosh_command.yml
    input_mapping: {manifest: generated-manifest-with-diego}
    params:
      BOSH_DIRECTOR: bosh.arya.cf-app.com
      BOSH_USER: {{arya_bosh_user}}
      BOSH_PASSWORD: {{arya_bosh_password}}
      DEPLOYMENT_YML: manifest/cf-deployment-with-diego.yml
      COMMAND: 'run errand acceptance_tests --keep-alive --download-logs --logs-dir bosh-logs'
    ensure:
      put: arya-acceptance-tests-with-diego-logs
      params:
        file: bosh-logs/acceptance_tests*.tgz
