groups:
- name: concourse
  jobs:
  - update-bosh-concourse
  - deploy-concourse

resource_types:
- name: bosh2-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
- name: bbl-state-resource
  type: docker-image
  source:
    repository: cfinfrastructure/bbl-state-resource

resources:
- name: gcp-xenial-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent

- name: capi-ci-private
  type: git
  source:
    branch: master
    private_key: ((private_key))
    uri: git@github.com:cloudfoundry/capi-ci-private.git

- name: capi-ci
  type: git
  source:
    branch: master
    private_key: ((private_key))
    uri: git@github.com:cloudfoundry/capi-ci.git

- name: concourse
  type: bosh-io-release
  source:
    repository: concourse/concourse-bosh-release

- name: garden-runc
  type: bosh-io-release
  source:
    repository: cloudfoundry/garden-runc-release

- name: postgres
  type: bosh-io-release
  source:
    repository: cloudfoundry/postgres-release

- name: bpm
  type: bosh-io-release
  source:
    repository: cloudfoundry/bpm-release

- name: ci-bbl-state
  type: bbl-state-resource
  source:
    bucket: ci-bbl-state
    iaas: gcp
    gcp_region: ((ci_gcp_region))
    gcp_service_account_key: ((ci_gcp_json_key))
    lb_type: concourse

- name: concourse-deployment
  type: bosh2-deployment
  source:
    skip_check: true
    deployment: concourse
    ignore_ssl: true
    vars_store:
      provider: gcs
      config:
        bucket: ((ci_bosh_vars_bucket))
        file_name: &ci_vars_store_path "bosh/vars-store.yml"
        json_key: ((ci_gcp_json_key))

# Scheduling
- name: weekly-sunday
  type: time
  source:
    location: America/Los_Angeles
    start: 23:00
    stop: 23:30
    days: [Sunday]

jobs:
- name: update-bosh-concourse
  serial: true
  plan:
    - in_parallel:
        steps:
        - get: capi-ci
        - get: capi-ci-private
        - get: weekly-sunday
          trigger: true
    - do:
      - put: ci-bbl-state
        params:
          state_dir: capi-ci-private/ci
          command: plan
          args:
            lb-type: concourse
      - put: ci-bbl-state
        params:
          command: up
          name_file: ci-bbl-state/name
      ensure:
        do:
        - get: ci-bbl-state
        - task: copy-and-commit-bbl-state
          file: capi-ci/ci/bbl-tasks/copy-and-commit-bbl-state.yml
          input_mapping:
            new-bbl-state: ci-bbl-state
            bbl-state-repo: capi-ci-private
          params:
            REPO_SUBDIRECTORY: "ci"
        - put: capi-ci-private
          params:
            repository: updated-bbl-state-repo
            rebase: true
        - task: run-bosh-cleanup
          file: capi-ci/ci/bbl-tasks/run-bosh-cleanup.yml
          input_mapping:
            bbl-state: capi-ci-private
          params:
            BBL_STATE_DIR: "ci"

- name: deploy-concourse
  serial: true
  interruptible: true
  plan:
  - aggregate:
    - get: concourse
      version:
        version: 5.3.0
    - get: garden-runc
    - get: bpm
    - get: postgres
      version: { version: '28' }
    - get: capi-ci-private
    - get: gcp-xenial-stemcell
    - get: capi-ci
    - get: ci-bbl-state
      passed: [update-bosh-concourse]
  - put: concourse-deployment
    params:
      source_file: ci-bbl-state/metadata
      manifest: capi-ci-private/ci/concourse.yml
      skip_drain:
        - worker
      releases:
        - concourse/release.tgz
        - garden-runc/release.tgz
        - postgres/*.tgz
        - bpm/*.tgz
      stemcells:
        - gcp-xenial-stemcell/*.tgz
