groups:
- name: retro-snacks
  jobs:
  - assign-and-alert-snack-tsar

resources:

- name: weekly-wednesday
  type: time
  source:
    location: America/Los_Angeles
    start: 10:00
    stop: 10:30
    days: [Wednesday]

- name: capi-ci
  type: git
  source:
    branch: main
    private_key: ((private_key))
    uri: git@github.com:cloudfoundry/capi-ci.git

- name: capi-ci-private
  type: git
  source:
    branch: main
    private_key: ((private_key))
    uri: git@github.com:cloudfoundry/capi-ci-private.git

jobs:

- name: assign-and-alert-snack-tsar
  plan:
  - get: weekly-wednesday
    trigger: true
  - get: capi-ci
  - get: capi-ci-private
  - task: assign-and-alert-snack-tsar
    file: capi-ci/ci/streamline-team/assign_snack_tsar.yml
    params:
      SLACK_API_TOKEN: ((slack_api_token))
      SLACK_CHANNEL_WEBHOOK_FOR_SNACKS: ((slack_channel_webhook_for_snacks))
