---
- type: replace
  path: /instance_groups/name=cc-deployment-updater?
  value:
   name: cc-deployment-updater
   networks:
   - name: default
   stemcell: default
   vm_type: small
   azs:
   - z1
   - z2
   instances: 1
   jobs:
   - name: cc_deployment_updater
     release: capi
     properties:
       cc:
         db_encryption_key: ((cc_db_encryption_key))
       ccdb:
         databases:
         - name: cloud_controller
           tag: cc
         db_scheme: mysql
         port: 3306
         roles:
         - name: cloud_controller
           password: ((cc_database_password))
           tag: admin
