- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/kubernetes?
  value:
    host_url: ((k8s_host_url))
    service_account:
      name: ((k8s_service_username))
      token: ((k8s_service_token))
    ca: ((k8s_node_ca))
    kpack:
      builder_namespace: 'cf-workloads'
      registry_service_account: 'gcr-service-account'
      registry_tag_base: gcr.io/(( gcr_project_name ))/capi-kpack-images  # variable needs to be supplied

