- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/kubernetes?
  value:
    host_url: ((k8s_host_url))
    service_account:
      name: ((k8s_service_username))
      token: ((k8s_service_account_data.token))
    ca: ((k8s_ca))
